name: ci-release
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v2

      - name: Set tags
        uses: actions/github-script@v7
        id: set_tags
        with:
          script: |
            const tag = context.ref.substring(10)
            const version = tag.replace('v', '')
            const [major, minor, patch] = version.split('.')
            core.setOutput('version', version)
            core.setOutput('major', major)
            core.setOutput('minor', `${major}.${minor}`)
            core.setOutput('major_minor_patch', version)

      - name: Get full version
        run: |
          echo "tag is ${{steps.set_tags.outputs.tag}}"
          echo "version full is ${{steps.set_tags.outputs.version}}"
          echo "version full is ${{steps.version.outputs.full}}"
          
      - name: Get major version
        run: |
          echo "tag is ${{steps.set_tags.outputs.tag}}"
          echo "major version is ${{steps.set_tags.outputs.major}}"
          echo "major version is ${{steps.version.outputs.major}}"
          
      - name: Get major_minor version
        run: |
          echo "tag is ${{steps.set_tags.outputs.tag}}"
          echo "minor version is ${{steps.set_tags.outputs.minor}}"
          echo "minor version is ${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}"
          
      - name: Get major_minor_patch version
        run: |
          echo "tag is ${{steps.set_tags.outputs.tag}}"
          echo "major_minor_patch version is ${{steps.set_tags.outputs.major_minor_patch}}"
          echo "major_minor_patch version is ${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}.${{steps.version.outputs}}"

      - name: Check prerelease
        if: ${{ github.event.release.prerelease == true }}
        run: |
          echo "This is a prerelease"

      - name: Check latest release
        if: ${{ github.event.release.prerelease == false }}
        run: |
          echo "This is the stable release"
          
