name: ci-release
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v2

      - name: Set tags
        uses: actions/github-script@v9
        id: set_tags
        with:
          script: |
            const tag = context.ref.substring(10)
            const version = tag.replace('v', '')
            const [major, minor, patch] = version.split('.')
            core.setOutput('version', version)
            core.setOutput('major', major)
            core.setOutput('minor', `${major}.${minor}`)
            core.setOutput('major_minor_patch', version)
          
      - name: Get parts
        run: |
          echo "version full is ${{steps.set_tags.outputs.version}}"
          echo "version full is ${{steps.version.outputs.full}}"
          echo "-------------------"
          echo "major version is ${{steps.set_tags.outputs.major}}"
          echo "major version is ${{steps.version.outputs.major}}"
          echo "-------------------"
          echo "minor version is ${{steps.set_tags.outputs.minor}}"
          echo "minor version is ${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}"
          
      - name: Check prerelease
        if: ${{ steps.version.outputs.prerelease != '' || steps.version.outputs.build != '' || github.event.release.prerelease == true }}
        run: |
          echo "prerelease is ${{steps.version.outputs.prerelease}}"
          echo "build is ${{steps.version.outputs.build}}"
          echo "This is a prerelease"

      - name: Check latest release
        if: ${{ steps.version.outputs.prerelease == '' && steps.version.outputs.build == '' && github.event.release.prerelease == false }}
        run: |
          echo "This is the stable release"
          
